#
# \author Arne Varholm
# \remarks Copyright 2003 Broadcom Corporation
# $Id: extractenums.py,v 1.9 2004/04/18 17:57:38 arne Exp $
#
# This file is autogenerated from header file
# ../../public/inc/common_defs.h by the extractenums.py script
#
UnknownTON = "0=UnknownTON"
InternationalTON = "1=InternationalTON"
NationalTON = "2=NationalTON"
NetworkSpecificTON = "3=NetworkSpecificTON"
DedicatedAccessTON = "4=DedicatedAccessTON"
DefaultAlphabetTON = "5=DefaultAlphabetTON"
UnknownNP = "0=UnknownNP"
ISDNNP = "1=ISDNNP"
DataNP = "3=DataNP"
TelexNP = "4=TelexNP"
NationalNP = "8=NationalNP"
PrivateNP = "9=PrivateNP"
