#
# \author Arne Varholm
# \remarks Copyright 2003 Broadcom Corporation
# $Id: extractenums.py,v 1.9 2004/04/18 17:57:38 arne Exp $
#
# This file is autogenerated from header file
# ../../phonebk/inc/phonebk.h by the extractenums.py script
#
PBK_EXT1 = "0=PBK_EXT1"
PBK_EXT2 = "1=PBK_EXT2"
