#
# \author Arne Varholm
# \remarks Copyright 2003 Broadcom Corporation
# $Id: extractenums.py,v 1.9 2004/04/18 17:57:38 arne Exp $
#
# This file is autogenerated from header file
# ../../public/inc/stk_def.h by the extractenums.py script
#
SATK_Result_NoCause = "0=SATK_Result_NoCause"
SATK_Result_ScreenBusy = "1=SATK_Result_ScreenBusy"
SATK_Result_BusyOnCall = "2=SATK_Result_BusyOnCall"
SATK_Result_BusyOnSS = "3=SATK_Result_BusyOnSS"
SATK_Result_NoService = "4=SATK_Result_NoService"
SATK_Result_RrNotGranted = "6=SATK_Result_RrNotGranted"
SATK_Result_NotInSpeechCall = "7=SATK_Result_NotInSpeechCall"
SATK_Result_BusyOnUSSD = "8=SATK_Result_BusyOnUSSD"
SATK_Result_BusyOnDtmf = "9=SATK_Result_BusyOnDtmf"
SATK_Result_Invalid2 = "10=SATK_Result_Invalid2"
